### ISSUE TITLE
running  webcam.py  error.

### ISSUE THREAD

**Issue by lvpinrui** [mrlooi/maskrcnn-benchmark#5]
hello,when running webcam.py has an error:
The configuration file used is  /configs/rotated/e2e_mask_rcnn_R_50_FPN_1x.yaml
python webcam.py 
Traceback (most recent call last):
  File "webcam.py", line 82, in <module>
    main()
  File "webcam.py", line 73, in main
    composite = coco_demo.run_on_opencv_image(img)
  File "/home/onkymask/anaconda3/envs/rotated_maskrcnn/lib/python3.7/site-packages/rotated_maskrcnn/demo/predictor.py", line 206, in run_on_opencv_image
    predictions = self.compute_prediction(image)
  File "/home/onkymask/anaconda3/envs/rotated_maskrcnn/lib/python3.7/site-packages/rotated_maskrcnn/demo/predictor.py", line 240, in compute_prediction
    predictions = self.model(image_list)
  File "/home/onkymask/anaconda3/envs/rotated_maskrcnn/lib/python3.7/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/onkymask/anaconda3/envs/rotated_maskrcnn/lib/python3.7/site-packages/rotated_maskrcnn/maskrcnn_benchmark/modeling/detector/generalized_rcnn.py", line 65, in forward
    features = self.backbone(images.tensors)
  File "/home/onkymask/anaconda3/envs/rotated_maskrcnn/lib/python3.7/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/onkymask/anaconda3/envs/rotated_maskrcnn/lib/python3.7/site-packages/torch/nn/modules/container.py", line 97, in forward
    input = module(input)
  File "/home/onkymask/anaconda3/envs/rotated_maskrcnn/lib/python3.7/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/onkymask/anaconda3/envs/rotated_maskrcnn/lib/python3.7/site-packages/rotated_maskrcnn/maskrcnn_benchmark/modeling/backbone/resnet.py", line 147, in forward
    x = self.stem(x)
  File "/home/onkymask/anaconda3/envs/rotated_maskrcnn/lib/python3.7/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/onkymask/anaconda3/envs/rotated_maskrcnn/lib/python3.7/site-packages/rotated_maskrcnn/maskrcnn_benchmark/modeling/backbone/resnet.py", line 362, in forward
    x = self.conv1(x)
  File "/home/onkymask/anaconda3/envs/rotated_maskrcnn/lib/python3.7/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/onkymask/anaconda3/envs/rotated_maskrcnn/lib/python3.7/site-packages/rotated_maskrcnn/maskrcnn_benchmark/layers/misc.py", line 33, in forward
    return super(Conv2d, self).forward(x)
  File "/home/onkymask/anaconda3/envs/rotated_maskrcnn/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 339, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: Expected 4-dimensional input for 4-dimensional weight [64, 3, 7, 7], but got 5-dimensional input of size [1, 1, 32, 800, 1066] instead
Can you give me some advice?waiting for your reply,thank you very much!

**Comment by mrlooi** [comment]
Hey I didn't update the webcam.py code from the original repo. Have a look at **my_tools/infer_demo.py**, you can adapt the webcam part easily with the infer_demo.py code

**Comment by lvpinrui** [comment]
> Hey I didn't update the webcam.py code from the original repo. Have a look at **my_tools/infer_demo.py**, you can adapt the webcam part easily with the infer_demo.py code

when running infer_demo has an error,my infer_demo.py is:
![image](https://user-images.githubusercontent.com/44189445/66816606-f2c4c900-ef6c-11e9-82aa-381ac3a66378.png)
error is:
![image](https://user-images.githubusercontent.com/44189445/66816656-08d28980-ef6d-11e9-8103-c8fb1fdee661.png)
Where should I change the configuration file?waiting for your reply

**Comment by mrlooi** [comment]
You're using the wrong infer_demo.py file (I guess I should remove this). Use the one in 'my_tools' folder. 
my_tools/infer_demo.py

**Comment by lvpinrui** [comment]
I tried it  as you said ,this is ok,thank you very much




------------------ 原始邮件 ------------------
发件人: "mrlooi"<notifications@github.com>;
发送时间: 2019年10月16日(星期三) 凌晨4:07
收件人: "mrlooi/rotated_maskrcnn"<rotated_maskrcnn@noreply.github.com>;
抄送: "。"<1358420042@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [mrlooi/rotated_maskrcnn] running  webcam.py  error. (#5)




You're using the wrong infer_demo.py file (I guess I should remove this). Use the one in 'my_tools' folder.
 my_tools/infer_demo.py
